name: Docker Compose Build

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images with Compose
        run: docker-compose build
